### ISSUE TITLE
How to properly handle errors on consumers?

### ISSUE THREAD

**Issue by geovanisouza92** [gocardless/hutch#218]
My current setup is:

- Rails 4 publisher
- JRuby 9k consumer

hutch.yml (configuration):

```yaml
mq_host: ...
mq_username: guest
mq_password: guest
mq_api_host: ...
channel_prefetch: 1
heartbeat: 150
require_paths:
  - foo.rb
error_handlers:
  - Logger
  - Sentry
error_acknowledgements:
  - Requeuer
```

Command: `hutch --config config/hutch.yaml`

I have a consumer executing a process that could raise some errors:

```ruby
class Foo
  include Hutch::Consumer
  consume 'foo'

  def process(message)
    # process that handle message and could raise errors
  end
end

class Requeuer < Hutch::Acknowledgements::Base
  def handle(delivery_info, properties, broker, ex)
    broker.requeue delivery_info.delivery_tag
    true
  end
end
```

Hunting down the issue, I:

- Started not handling the errors, but as discussed in #195, this could be dangerous considering the Thread pool nature of AMQP client.
- Then I tried just capturing and requeue'ing the message, but this clashes with `@broker.ack` on `Hutch::Worker#handle_message`, sending an `requeue` and `ack` messages to RabbitMQ, broking the protocol.
- Then I tried the code above, that requeue and raise the error, but ended with `hutch shut down gracefully` in the middle of processing.

Considering #165, acking manually seems to be the best option, taking into account that as said in #195, the library could not decided whether if the worker/consumer should crashes due an unhandled exception.

This issue is more a doubt about what is the correct way to handle the errors on consumers?
